services:
  analytics:
    build:
      context: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./gradlew bootRun --no-daemon
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/linkdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      IPINFO_TOKEN: ${IPINFO_TOKEN}
    networks:
      - appnet

networks:
  appnet:
    external: true
