spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://postgres:5432/linkdb
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_analytics_history
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: analytics-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

ipinfo:
  token: ${IPINFO_TOKEN}